#!/bin/bash
# Turn ROOL's stock disc into one that will boot into the anyvm agent.
#
# Runs right after _prep_vhd_disk() has produced $VM_WORK_QCOW and before
# createVMFromVHD() builds the QEMU command line -- which matters, because
# VM_BIOS is read when that command line is assembled, and the ROM this hook
# extracts is what it points at.
#
# This is deliberately NOT in beforeBuild: clearVM() runs between the two and
# deletes <osname>.qcow2 and <osname>.img, so an image prepared that early is
# thrown away and silently replaced by a pristine one.
#
# Three things happen:
#   1. resize to a power of two -- QEMU's SD card model requires it, and
#      ROOL's image is 1966080000 bytes.
#   2. lift RISCOS.IMG out of the FAT boot partition, so the ROM always
#      matches the release instead of being fetched separately.
#   3. patch one cosmetic boot script with a bootstrap that fetches the agent.
#
# On (3): RISC OS copies $.!Boot.RO530Hook.Boot into $.!Boot.Choices.Boot on
# FIRST boot, so the TEMPLATE is what has to be patched -- the Choices tree
# does not exist yet in a never-booted image, and patching it would silently
# do nothing.  TimeSetup is the host because it is the largest cosmetic Tasks
# file (332 bytes) and Tasks entries run once the desktop is up; a PreDesk
# hook is too early for the 6200K WimpSlot the interpreter needs (error &1C1).
# hooks/host_finalizeImage.sh puts it back after the build.

set -euo pipefail

WORK="${VM_WORKDIR:-build}"
QCOW="${VM_WORK_QCOW:-${VM_OS_NAME}.qcow2}"
HERE="$(cd "$(dirname "$0")" && pwd)"
TOOL="$HERE/../files/rofilecore.py"
NBD=/dev/nbd0
TEMPLATE='$.!Boot.RO530Hook.Boot.Tasks.TimeSetup'
STOCK_PREFIX='| This file was automatically generated by !TimeSetup'
PAD=$((4 * 1024 * 1024 * 1024))

echo "=== riscos prepareImage ==="

echo "--- resizing to $PAD (QEMU's SD model needs a power of two) ---"
qemu-img resize "$QCOW" "$PAD"
qemu-img info "$QCOW" | sed 's/^/    /'

_cleanup() { sudo qemu-nbd --disconnect "$NBD" 2>/dev/null || true; }
trap _cleanup EXIT

sudo modprobe nbd max_part=16
sudo qemu-nbd --disconnect "$NBD" 2>/dev/null || true
sudo qemu-nbd --connect="$NBD" "$QCOW"
sudo partprobe "$NBD" 2>/dev/null || true
sleep 2
sudo chmod 0666 "$NBD" 2>/dev/null || true

echo "--- partitions ---"
sudo fdisk -l "$NBD" | sed 's/^/    /'

# The ROM, from the image's own FAT boot partition.
echo "--- extracting RISCOS.IMG ---"
fat_start=$(sudo partx -g -o START -n 1:1 "$NBD" | tr -d ' ')
if [ -z "$fat_start" ]; then
    echo "FATAL: could not read the FAT partition offset" >&2
    exit 1
fi
echo "    FAT partition at sector $fat_start"
MTOOLS_SKIP_CHECK=1 mcopy -o -i "${NBD}@@$((fat_start * 512))" ::RISCOS.IMG "$WORK/RISCOS.IMG"
ls -l "$WORK/RISCOS.IMG"

# Keep the stock script so host_finalizeImage.sh can put it back.
python3 "$TOOL" "$NBD" cat "$TEMPLATE" --prefix "$STOCK_PREFIX" > "$WORK/TimeSetup.orig"
wc -c "$WORK/TimeSetup.orig"

# The bootstrap. Build-time scaffold only: once the agent is up,
# hooks/host_enablessh.py writes it to disc as a real file with a real Tasks
# entry, and host_finalizeImage.sh restores this script, so the shipped image
# has no HTTP bootstrap and a stock TimeSetup.
AGENT_URL="http://10.0.2.2:${VM_AGENT_HTTP_PORT:-8099}/anyvmd.py"
cat > "$WORK/bootstrap.obey" <<EOF
X Obey \$.Programming.Python.!Python27.!Boot
X WimpSlot -min 6200k
X /<Python27\$Dir>.python27 -c "import urllib;exec(urllib.urlopen('$AGENT_URL').read())" { > <Wimp\$ScrapDir>.avmout }
EOF
echo "--- bootstrap ---"
sed 's/^/    /' "$WORK/bootstrap.obey"

python3 "$TOOL" "$NBD" patch "$TEMPLATE" "$WORK/bootstrap.obey" --prefix "$STOCK_PREFIX"

echo "--- verify ---"
python3 "$TOOL" "$NBD" cat "$TEMPLATE" --prefix 'X Obey' | sed 's/^/    /'

sync
sudo qemu-nbd --disconnect "$NBD"

# `qemu-nbd --disconnect` returns once the kernel client is gone, but the
# server process still holds an exclusive write lock and exits asynchronously;
# the launch that follows needs that lock. Wait for both signals, same as
# reactos-builder's files/inject.sh and plan9-builder's prepareImage hook.
_nbd_name="$(basename "$NBD")"
for _try in $(seq 1 120); do
    if [ ! -e "/sys/block/${_nbd_name}/pid" ] \
       && qemu-img resize "$QCOW" +0 >/dev/null 2>&1; then
        break
    fi
    sleep 0.5
done
trap - EXIT
sudo chmod 0666 "$QCOW" 2>/dev/null || true

echo "=== riscos prepareImage: done ==="
