#!/bin/bash
# Turn ROOL's stock disc into one that will boot into the anyvm agent.
#
# Runs right after _prep_vhd_disk() has produced $VM_WORK_QCOW and before
# createVMFromVHD() builds the QEMU command line -- which matters, because
# VM_BIOS is read when that command line is assembled, and the ROM this hook
# extracts is what it points at.
#
# This is deliberately NOT in beforeBuild: clearVM() runs between the two and
# deletes <osname>.qcow2 and <osname>.img, so an image prepared that early is
# thrown away and silently replaced by a pristine one.
#
# Three things happen:
#   1. resize to 4 GiB, because QEMU will not attach ROOL's disc as an SD
#      card at its native size. sd_realize() in hw/sd/sd.c enforces two
#      different rules depending on which side of SDSC_MAX_CAPACITY (2 GiB,
#      sd.c:58) the image falls on: at or below it the size must be a power
#      of two, above it a non-eMMC card only has to be a multiple of 512 KiB.
#      ROOL's image is 1966080000 bytes -- just under the 2 GiB line, so it
#      lands in the power-of-two branch and is rejected. 4 GiB clears the
#      line and satisfies both rules, which is also why
#      hooks/host_finalizeImage.sh can shrink back to exactly this size after
#      the engine has padded the disc out to 204 GiB.
#   2. lift RISCOS.IMG out of the FAT boot partition, so the ROM always
#      matches the release instead of being fetched separately.
#   3. patch one cosmetic boot script with a bootstrap that fetches the agent.
#
# On (3): RISC OS copies $.!Boot.RO530Hook.Boot into $.!Boot.Choices.Boot on
# FIRST boot, so the TEMPLATE is what has to be patched -- the Choices tree
# does not exist yet in a never-booted image, and patching it would silently
# do nothing.  TimeSetup is the host because it is the largest cosmetic Tasks
# file (332 bytes) and Tasks entries run once the desktop is up; a PreDesk
# hook is too early for the 6200K WimpSlot the interpreter needs (error &1C1).
# hooks/host_finalizeImage.sh puts it back after the build.

set -euo pipefail

WORK="${VM_WORKDIR:-build}"
QCOW="${VM_WORK_QCOW:-${VM_OS_NAME}.qcow2}"
HERE="$(cd "$(dirname "$0")" && pwd)"
TOOL="$HERE/../files/rofilecore.py"
NBD=/dev/nbd0
TEMPLATE='$.!Boot.RO530Hook.Boot.Tasks.TimeSetup'
STOCK_PREFIX='| This file was automatically generated by !TimeSetup'
PAD=$((4 * 1024 * 1024 * 1024))

echo "=== riscos prepareImage ==="

echo "--- resizing to $PAD (clears QEMU's 2 GiB SDSC power-of-two rule) ---"
qemu-img resize "$QCOW" "$PAD"
qemu-img info "$QCOW" | sed 's/^/    /'

_cleanup() { sudo qemu-nbd --disconnect "$NBD" 2>/dev/null || true; }
trap _cleanup EXIT

sudo modprobe nbd max_part=16
sudo qemu-nbd --disconnect "$NBD" 2>/dev/null || true
sudo qemu-nbd --connect="$NBD" "$QCOW"
sudo partprobe "$NBD" 2>/dev/null || true
sleep 2
sudo chmod 0666 "$NBD" 2>/dev/null || true

echo "--- partitions ---"
sudo fdisk -l "$NBD" | sed 's/^/    /'

# The ROM, from the image's own FAT boot partition.
echo "--- extracting RISCOS.IMG ---"
fat_start=$(sudo partx -g -o START -n 1:1 "$NBD" | tr -d ' ')
if [ -z "$fat_start" ]; then
    echo "FATAL: could not read the FAT partition offset" >&2
    exit 1
fi
echo "    FAT partition at sector $fat_start"
MTOOLS_SKIP_CHECK=1 mcopy -o -i "${NBD}@@$((fat_start * 512))" ::RISCOS.IMG "$WORK/RISCOS.IMG"
ls -l "$WORK/RISCOS.IMG"

# Keep the stock script so host_finalizeImage.sh can put it back.
python3 "$TOOL" "$NBD" cat "$TEMPLATE" --prefix "$STOCK_PREFIX" > "$WORK/TimeSetup.orig"
wc -c "$WORK/TimeSetup.orig"

# The bootstrap. Build-time scaffold only: once the agent is up,
# hooks/host_enablessh.py writes it to disc as a real file with a real Tasks
# entry, and host_finalizeImage.sh restores this script, so the shipped image
# has no HTTP bootstrap and a stock TimeSetup.
#
# 192.168.122.1:8000 is build.py's own web server (startWeb) serving the repo
# root -- the same host and port ghostbsd fetches its answer file from. NOT
# 10.0.2.2: that is QEMU's default slirp gateway, but build.py overrides the
# network to net=192.168.122.0/24,host=192.168.122.1, so the default address
# is nobody here. (A bare `-netdev user` does give 10.0.2.2, which is why
# local testing outside the builder never noticed.)
AGENT_URL="http://192.168.122.1:8000/files/anyvmd.py"
cat > "$WORK/bootstrap.obey" <<EOF
X Obey \$.Programming.Python.!Python27.!Boot
X WimpSlot -min 6200k
X /<Python27\$Dir>.python27 -c "import urllib;exec(urllib.urlopen('$AGENT_URL').read())" { > <Wimp\$ScrapDir>.avmout }
EOF
echo "--- bootstrap ---"
sed 's/^/    /' "$WORK/bootstrap.obey"

# hooks/host_finalizeImage.sh scans the finished disc for this exact string to
# prove no bootstrap survived into the shipped image. Hand it the URL rather
# than letting it invent its own marker: the URL is the one part of the
# bootstrap nothing else on the volume can contain. Matching on the code
# instead does NOT work -- a `urllib.urlopen` scan finds 21 hits on a stock
# RISC OS disc, all of them Python 2.7's own urllib.py, its .pyc and its test
# suite, so that check could never pass.
printf '%s\n' "$AGENT_URL" > "$WORK/bootstrap.marker"

python3 "$TOOL" "$NBD" patch "$TEMPLATE" "$WORK/bootstrap.obey" --prefix "$STOCK_PREFIX"

echo "--- verify ---"
python3 "$TOOL" "$NBD" cat "$TEMPLATE" --prefix 'X Obey' | sed 's/^/    /'

sync
sudo qemu-nbd --disconnect "$NBD"

# `qemu-nbd --disconnect` returns once the kernel client is gone, but the
# server process still holds an exclusive write lock and exits asynchronously;
# the launch that follows needs that lock. Wait for both signals, same as
# reactos-builder's files/inject.sh and plan9-builder's prepareImage hook.
_nbd_name="$(basename "$NBD")"
for _try in $(seq 1 120); do
    if [ ! -e "/sys/block/${_nbd_name}/pid" ] \
       && qemu-img resize "$QCOW" +0 >/dev/null 2>&1; then
        break
    fi
    sleep 0.5
done
trap - EXIT
sudo chmod 0666 "$QCOW" 2>/dev/null || true

echo "=== riscos prepareImage: done ==="
